---
version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 5
      commit-message:
          prefix: chore(actions)
      labels:
          - dependencies
          - github-actions

    - package-ecosystem: pip
      directory: /docs
      schedule:
          interval: weekly
          day: monday
      open-pull-requests-limit: 3
      commit-message:
          prefix: chore(docs)
      labels:
          - dependencies
          - docs
      groups:
          mkdocs:
              patterns:
                  - mkdocs*
                  - pymdown*
