[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/claude-code-config"]
    type = "git-repo"
    url = "https://github.com/edjchapman/claude-code-config.git"
    refreshPeriod = "168h"
    [".config/claude-code-config".pull]
        rebase = true
